targets:
  $default:
    builders:
      freezed:
        options:
          when:
            when: false
            when_or_null: false
            maybe_when: false
          map:
            map: false
            map_or_null: false
            maybe_map: false
      riverpod_generator:
        options:
          provider_name_suffix: "Pod"
